# src/paths.py

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
CLEAN_DATA_DIR = DATA_DIR / "clean"

ANALYSIS_DIR = PROJECT_ROOT / "analysis"

REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"
TABLES_DIR = REPORTS_DIR / "tables"
CLUSTERS_DIR = TABLES_DIR / "clusters"

PHASE1_FIGURES_DIR = FIGURES_DIR / "phase1"
PHASE2_FIGURES_DIR = FIGURES_DIR / "phase2"
PHASE3_FIGURES_DIR = FIGURES_DIR / "phase3"
PHASE4_FIGURES_DIR = FIGURES_DIR / "phase4"

PHASE1_TABLES_DIR = TABLES_DIR / "phase1"
PHASE2_TABLES_DIR = TABLES_DIR / "phase2"
PHASE3_TABLES_DIR = TABLES_DIR / "phase3"
PHASE4_TABLES_DIR = TABLES_DIR / "phase4"
